### ISSUE TITLE
How does this compare to DXDIAG?

### ISSUE THREAD

**Issue by VZout** [sawickiap/D3d12info#1]
Like I mentioned in the title: How does this compare to DXDIAG which is already installed on every windows pc? This might be something you want to write about in your README.md

**Comment by sawickiap** [comment]
That's a good idea, thanks! I will compare them and document. I think my tool is more similar to dxcapsviewer.exe that can be found in c:\Program Files (x86)\Windows Kits\10\bin\...\x64\, only console-based and not GUI.
