### ISSUE TITLE
Update to NVAPI 535 for NVAPI_D3D12_RAYTRACING_CAPS_TYPE_DISPLACEMENT_MICROMAP..

### ISSUE THREAD

**Issue by oscarbg** [sawickiap/D3d12info#11]
Hi,
seems NVAPI R535 adds DMM to D3D12 via NVAPI..
thanks..

**Comment by sawickiap** [comment]
Hi,
Thanks for the heads-up about the new version of NVAPI. I updated it and created new release 1.6.0.

**Comment by oscarbg** [comment]
no problem.. really thanks for this little project!
