### ISSUE TITLE
AgilitySDK 1.613 support..

### ISSUE THREAD

**Issue by oscarbg** [sawickiap/D3d12info#18]
Hi,
today is SM6.8 official release..
hope d3d12info (non preview executable) can be updated eventually..
thanks..

**Comment by sawickiap** [comment]
OK, done :)

**Comment by oscarbg** [comment]
thanks.. and sorry for asking for an update, for every new NVAPI or Agility SDK release.. :-)

**Comment by sawickiap** [comment]
That's fine, please keep them coming! I may not follow the news every day, so a notification is welcome.
