### ISSUE TITLE
WDDM Caps/Feature support display

### ISSUE THREAD

**Issue by TheFireKahuna** [sawickiap/D3d12info#22]
Any chance of also including the new WDDM 3.2 API for reporting of supported driver features?

https://learn.microsoft.com/en-us/windows-hardware/drivers/display/querying-wddm-feature-support-and-enablement

via

https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmthk/nf-d3dkmthk-d3dkmtisfeatureenabled

With these new API's it would be interesting to see if features such as Native GPU fence objects, DIrty-bit tracking or IOMMU remapping/isolation are supported for a given card, or if Hardware flip queue is enabled within a driver. 

Good list of possible inclusions here with individual structures for each supported feature.
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmddi/ne-d3dkmddi-_dxgk_queryadapterinfotype

**Comment by sawickiap** [comment]
I am sorry, but Windows Display Driver Model (WDDM) is a separate API that is out of scope of this project. As it name suggests, it is intended for developers of display drivers on Windows to communicate with the OS. On the other hand, D3d12info is intended for game developers who develop their applications for Windows using D3D12.
