### ISSUE TITLE
Can't build or run - parts of DirectX 12 Agility SDK 1.706.3-preview missing

### ISSUE THREAD

**Issue by didito** [sawickiap/D3d12info#3]
Hi,

Great tool. I appreciate the updates.

I tried to build your project and it turns out parts of your DirectX 12 Agility SDK 1.706.3-preview are missing. In particular the "build" sub folder, which

1. contains the header(s) you include in pch.hpp
2. contains the DLL(s) we need at runtime

The reason is the first line in your .gitignore.

Ideally the project would also copy the DLLs (and PDBs) from the package `<repository>\Src\ThirdParty\microsoft.direct3d.d3d12.1.706.3-preview\build\native\bin\x64` to the [D3D12SDKPath](https://github.com/sawickiap/D3d12info/blob/master/Src/Main.cpp#L13) `<repository>\Src\build\d3d12` as a build step. In the current project configuration we probably only have to worry about x64.

The release is fine, it contains `D3D12\D3D12Core.dll`.

Btw, diffing your version of 1.706.3-preview with a [freshly downloaded one](https://www.nuget.org/packages/Microsoft.Direct3D.D3D12/1.706.3-preview) shows additional differences. You might want to fully replace.

Thanks!

**Comment by sawickiap** [comment]
Please let me know if commit ce4d1681a81addd3e394ec3660c834270755f4c7 fixes the problem.
