### ISSUE TITLE
Consider to set USE_AGS, USE_NVAPI and USE_VULKAN to 0 as default

### ISSUE THREAD

**Issue by didito** [sawickiap/D3d12info#4]
It's a minor thing and probably not what you personally want, but I think the out-of-the-box experience for people without these dependencies would be better that way. Especially since the repository or project is not set up for them.

**Comment by sawickiap** [comment]
I prefer to have them enabled by default. But you are right, it would be better if the project compiled for other developers out-of-the-box. In the future I plan to use CMake and make those parameters of CMake.

**Comment by sawickiap** [comment]
Please let me know if commit ce4d1681a81addd3e394ec3660c834270755f4c7 fixes the problem.
