### ISSUE TITLE
NvAPI_GPU_GetMemoryInfoEx wrong sizes

### ISSUE THREAD

**Issue by StefanG3D** [sawickiap/D3d12info#7]
Lines 600 ff in NvApiData.cpp 
_Print_sizeKilobytes..._
produce wrong output:
    NvAPI_GPU_GetMemoryInfoEx - NV_GPU_MEMORY_INFO_EX::dedicatedVideoMemory = 8589934592 (0x200000000) KB (8.00 TB)

8 TERABYTES???

as opposed to
DXGI_ADAPTER_DESC3:
    DedicatedVideoMemory = 8421113856 (0x1f5f00000) (7.84 GB)

~8 GIGABYTES correct

**Comment by sawickiap** [comment]
Thank you for reporting this bug! I fixed it and created new release.
