### ISSUE TITLE
add missing D3D12_FEATURE_DATA_D3D12_OPTIONS12::RelaxedFormatCastingSupported

### ISSUE THREAD

**Issue by didito** [sawickiap/D3d12info#9]
> RelaxedFormatCastingSupported
> 
> Type: _Out_ [BOOL](https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types)
> 
> Technically used to indicate support for the functionality that enables integer aliasing.
> 
> Requires the DirectX 12 Agility SDK 1.7 or later; otherwise, the value is always FALSE.

https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_feature_data_d3d12_options12

I guess fix would be to add

`Print_BOOL(L"RelaxedFormatCastingSupported",` o.RelaxedFormatCastingSupported);

within https://github.com/sawickiap/D3d12info/blob/master/Src/Main.cpp#L283

**Comment by sawickiap** [comment]
Thank you for finding this bug! I don't know how could I miss that property 😀 I fixed it and I created release 1.5.1.
